spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acme_transactions
    username: acme
    password: w3x_assE55ment
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
treasury:
  exchange:
    rates:
      url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange?fields=record_date,country,currency,country_currency_desc,exchange_rate,effective_date&sort=-record_date&page[size]=1000
server:
  port: 8080 